version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb+srv://test_user:cxPSAO82hE4M9MCk@connectmoney.497pv.mongodb.net/?retryWrites=true&w=majority&appName=ConnectMoney
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test_user
      - MONGO_INITDB_ROOT_PASSWORD=cxPSAO82hE4M9MCk
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: